<?php
/**
 * Created by PhpStorm.
 * User: medric
 * Date: 23/12/18
 * Time: 20:05
 */

namespace app\controllers;

use app\managers\MemberSessionManager;
use app\models\forms\UpdateSocialInformationForm;
use app\models\forms\UpdatePasswordForm;
use app\models\forms\NewMemberForm;
use app\managers\RedirectionManager;
use app\models\Member;
use app\models\User;
use app\models\Saving;
use app\models\forms\IdForm;
use app\models\forms\NewBorrowingForm;
use app\models\forms\NewRefundForm;
use app\models\forms\NewSavingForm;
use app\models\forms\NewSessionForm;
use app\models\Administrator;
use app\models\Help_type;
use app\models\Contribution;
use app\models\Session;
use app\models\Help;
use app\models\Exercise;
use app\models\Borrowing;
use yii\web\Controller;
use yii\web\UploadedFile;
use DateTime;
use Yii;
use yii\base\Security;
use yii\data\Pagination;
use app\managers\FileManager;

class MemberController extends Controller
{

    public $layout = "member_base";
    public $defaultAction = "accueil";
    public $user;
    public $member;
//*********************************************************************************** */
    public function beforeAction($action)
    {
        if (!\Yii::$app->user->getIsGuest()) {
            $user = User::findOne(\Yii::$app->user->getId());

            if ($user->type === "MEMBER")
            {
                $member = Member::findOne(['user_id'=> $user->id]);

                $this->user = $user;
                $this->member = $member;
                $this->view->params = ['user'=> $this->user,'member'=> $this->member];

                return parent::beforeAction($action);
            } // TODO: Change the autogenerated stub
            elseif ( $user->type === "ADMINISTRATOR") {
                {
                    \Yii::$app->response->redirect("@administrator.home");
                }
            }
            else
                return RedirectionManager::abort($this);
        }
        else
        {
            \Yii::$app->response->redirect("@guest.connection");
        }

    }
/***************************action accueil************************************************* */
    public function actionAccueil() {
        MemberSessionManager::setHome();
        $session = Session::findOne(['active' => true]);
        $idModel = new IdForm();
        if ($session)
            $idModel->id = $session->id;
        $model = new NewSessionForm();
        return $this->render('home',compact('session','model','idModel'));
    }
/*********************************action de deconnexion à modifier ************************************************* */
    public function actionDeconnexion() {
        if (\Yii::$app->request->post()) {
            \Yii::$app->user->logout();
            return $this->redirect('@guest.connection');
        }
        {
            return $this->redirect('@member.home');
        }
    }
/********************************action profil *************************************************** */
    public function actionProfil() {
        
        MemberSessionManager::setProfil();
            $user = User::findOne(\Yii::$app->user->getId());
                $member = Member::findOne(['user_id'=> $user->id]);

                $this->user = $user;
                $this->member = $member;
                $this->view->params = ['user'=> $this->user,'member'=> $this->member];
                return $this->render('profil',['member'=> $member, 'user'=> $user]);
            
        
    }
/*******************************profil Membre ******************************************************* */
    public function actionProfilMembre($m=0, $n=0) {
        MemberSessionManager::setMembers();
       if($m){
            $member = Member::findOne($n);
            $user = User::findOne($m);
            
            return $this->render('profilmembre',['member'=> $member, 'user'=> $user]);
       }
    }
/****************************profil administrateur ******************************************************* */
    public function actionProfilAdmin($m=0, $n=0) {
        MemberSessionManager::setAdministrators();
        if($m){
             $admin = Administrator::findOne($n);
             $user = User::findOne($m);
             
             return $this->render('profiladmin',['admin'=> $admin, 'user'=> $user]);
        }
     }
/*****************************modifier Profil**************************************************** */
    public function actionModifierProfil() {
        MemberSessionManager::setProfil();
        $user = User::findOne(\Yii::$app->user->getId());
        $member = Member::findOne(['user_id'=> $user->id]);
        $socialModel = new UpdateSocialInformationForm();
        $passwordModel = new UpdatePasswordForm();

        $socialModel->attributes = [
            'username' => $this->member->username,
            'name' => $this->user->name,
            'first_name' => $this->user->first_name,
            'tel' => $this->user->tel,
            'email' => $this->user->email,
            'address' => $this->user->address,
        ];

        return $this->render('modifier_profil',compact('socialModel','passwordModel'));
        
    }
/*****************************Enregister les modifications du profil ****************************************************** */
    public function actionEnregistrerModifierProfil() {
        MemberSessionManager::setProfil();
        if (\Yii::$app->request->getIsPost()) {
            $socialModel = new UpdateSocialInformationForm();
            $passwordModel = new UpdatePasswordForm();

            if ($socialModel->load(\Yii::$app->request->post()) &&  $socialModel->validate()) {
                $this->user->name = $socialModel->name;
                $this->user->first_name = $socialModel->first_name;
                $this->user->tel = $socialModel->tel;
                $this->user->email = $socialModel->email;
                $this->user->address = $socialModel->address;
              /*  if (UploadedFile::getInstance($socialModel,"avatar"))
                    $this->user->avatar = FileManager::storeAvatar( UploadedFile::getInstance($socialModel,"avatar"),$socialModel->username,"MEMBER");
*/
            if (UploadedFile::getInstance($socialModel,"avatar"))
                {
                     $this->user->avatar=UploadedFile::getInstance($socialModel,'avatar');
                    $this->user->avatar->saveAs('img/upload/'.$this->user->avatar->basename.'.'.$this->user->avatar->extension);
                    $socialModel->avatar=$this->user->avatar->basename.'.'.$this->user->avatar->extension;
                }
            else{
                    $this->user->avatar=null;
                }
 
                $this->user->save();
                $this->member->username = $socialModel->username;
                $this->member->save();
                return $this->redirect("@member.profil");
            }
            else
                return $this->render('modifier_profil',compact('socialModel','passwordModel'));

        }
        else
        {
            return RedirectionManager::abort($this);;
        }

    }
/*******************Modifier le mots de passe ******************************************* */
    public function actionModifierMotDePasse() {
        MemberSessionManager::setProfil();
        if (\Yii::$app->request->getIsPost()) {
            $socialModel = new UpdateSocialInformationForm();
            $socialModel->attributes = [
                'username' => $this->member->username,
                'name' => $this->user->name,
                'first_name' => $this->user->first_name,
                'tel' => $this->user->tel,
                'email' => $this->user->email,
                'address' => $this->user->address,
            ];

            $passwordModel = new UpdatePasswordForm();
            if ($passwordModel->load(\Yii::$app->request->post()) &&  $passwordModel->validate()) {
                if ($this->user->validatePassword($passwordModel->password)) {
                    $this->user->password = Yii::$app->getSecurity()->generatePasswordHash($passwordModel->new_password);
                    $this->user->save();
                    return $this->redirect("@member.profil");
                }
                else {
                    $passwordModel->addError('password','Le mot de passe ne correspond pas');
                    return $this->render('modifier_profil',compact('socialModel','passwordModel'));
                }

            }
            else
                return $this->render('modifier_profil',compact('socialModel','passwordModel'));

        }
        else
            return RedirectionManager::abort($this);;
    }
/****************************action sur les types d'aide niveau ******************************************************* */
    public function actionTypesAide() {
        MemberSessionManager::setHelps();
        $helptype = Help_type::find()->all();
        return $this->render('types_aide',compact('helptype'));
    }
/***************************par rapport au membre ********************************************* */
    public function actionMembres() {
        MemberSessionManager::setMembers();
        $user = User::findOne(\Yii::$app->user->getId());
        $member = Member::findOne(['user_id'=> $user->id]);
        $members = Member::findBySql('Select * from member where id != '.$member->id)->all();
        return $this->render('members',compact('members'));
    }
/***************************par rapport à l'administration *********************************************************** */
    public function actionAdministrators() {
        MemberSessionManager::setAdministrators();
        $administrators = Administrator::find()->all();
        return $this->render('administrators',compact('administrators'));
    }
/************************action sur les épargnes *************************************************** */
    public function actionEpargnes() {
        MemberSessionManager::setHome("epargnes");
        $model = new NewSavingForm();
        $user = User::findOne(\Yii::$app->user->getId());
        $member = Member::findOne(['user_id'=> $user->id]);
        $query = Exercise::find();
        $pagination = new Pagination([
            'defaultPageSize' => 1,
            'totalCount' => $query->count(),
        ]);

        $exercises = $query->orderBy(['created_at'=> SORT_DESC])
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render("epargnes",compact("exercises","pagination","member"));
    }
/*********************************action emprunts************************************************************** */
    public function actionEmprunts() {
        MemberSessionManager::setHome("emprunts");
        $user = User::findOne(\Yii::$app->user->getId());
        $member = Member::findOne(['user_id'=> $user->id]);
        $model = new NewBorrowingForm();

        $query = Exercise::find();
        $pagination = new Pagination([
            'defaultPageSize' => 1,
            'totalCount' => $query->count(),
        ]);

        $exercises = $query->orderBy(['created_at'=> SORT_DESC])
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render("emprunts",compact("exercises","pagination","member"));
    }
    /*************************action sur les contributions ****************************************************** */
    public function actionContributions() {
        MemberSessionManager::setHome("contributions");
        $user = User::findOne(\Yii::$app->user->getId());
        $member = Member::findOne(['user_id'=> $user->id]);
        $contributions = Contribution::find()->where(['member_id'=> $member->id])->all();
        return $this->render('contributions',compact('contributions'));
    }
/**********************************action sur les sessions *************************************************************************** */
    public function actionSessions() {
        MemberSessionManager::setHome("sessions");
        $query = Exercise::find();
        $pagination = new Pagination([
            'defaultPageSize' => 1,
            'totalCount' => $query->count(),
        ]);

        $exercises = $query->orderBy(['created_at'=> SORT_DESC])
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();
        return $this->render("sessions",compact('exercises','pagination'));
    }
/*******************************detail de la session utilisateur **************************************************************** */
    public function actionDetailSession($q = 0) {
        MemberSessionManager::setHome("sessions");
        if ($q) {
            $session = Session::findOne($q);
            if ($session) {
                return $this->render("detailsession",compact('session'));
            }
            else
                return RedirectionManager::abort($this);
        }
        else
            return RedirectionManager::abort($this);
    }
/******************************action sur les exercices ********************************************************************************* */
    public function actionExercises() {
        MemberSessionManager::setHome("exercises");
        $query = Exercise::find();

        $user = User::findOne(\Yii::$app->user->getId());
        $member = Member::findOne(['user_id'=> $user->id]);

        $pagination = new Pagination([
            'defaultPageSize' => 1,
            'totalCount' => $query->count(),
        ]);
        $exercises = $query->orderBy(['created_at'=> SORT_DESC])
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();
        return $this->render("exercises",compact('exercises','pagination',"member"));
    }
/***************************actions sur les Aides *************************************************************** */
    public function actionAides() {
        MemberSessionManager::setHome("helps");

        $activeHelps = Help::findAll(['state' => true]);

        $query = Help::find()->where(['state' => false])->orderBy('created_at',SORT_DESC);

        $pagination = new Pagination([
            'defaultPageSize' => 9,
            'totalCount' => $query->count(),
        ]);

        $helps = $query
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render("helps",compact("helps",'pagination',"activeHelps"));
    }

    /*****************************detail de l'aide **************************************************************** */
    public function actionDetailAide($q=0) {
        if ($q) {
            $help = Help::findOne($q);
            if ($help) {

                return $this->render("help_details",compact("help"));
            }
            else
                return RedirectionManager::abort($this);
        }
        else
            return RedirectionManager::abort($this);
    }

}